# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ronanpoder <ronanpoder@student.42.fr>      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/12/05 23:02:14 by rpoder            #+#    #+#              #
#    Updated: 2022/05/29 18:28:11 by ronanpoder       ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libftprintf.a
CC = cc
CFLAGS = -Wall -Werror -Wextra
INC = -I includes
SRCDIR = ./src/

SRCS =	$(addprefix $(SRCDIR), \
	ft_isalpha.c ft_isdigit.c ft_isalnum.c ft_isascii.c ft_isprint.c ft_tolower.c ft_toupper.c \
	ft_strlen.c ft_strchr.c \
	ft_strchr.c ft_atoi.c ft_memset.c \
	ft_bzero.c ft_memmove.c ft_memcpy.c ft_strlcpy.c ft_strnstr.c ft_strncmp.c ft_substr.c \
	ft_strdup.c ft_calloc.c ft_strlcat.c ft_strjoin.c ft_strtrim.c ft_strrchr.c ft_memchr.c ft_memcmp.c \
	ft_memcpy.c ft_split.c ft_itoa.c ft_putchar_fd.c ft_putstr_fd.c ft_putendl_fd.c ft_putnbr_fd.c ft_strmapi.c ft_striteri.c \
	ft_convert_base.c ft_str_applyft.c ft_convert_base.c \
	ft_printf.c \
	ft_printf_utils.c \
	ft_handle_parser.c \
	ft_lstnew.c ft_lstadd_front.c ft_lstsize.c ft_lstlast.c ft_lstadd_back.c ft_lstdelone.c \
	ft_lstclear.c ft_lstiter.c)

OBJS = ${SRCS:.c=.o}

all: ${NAME}

%.o: %.c
	$(CC) $< $(CFLAGS) $(INC) -c -o $@

$(NAME): ${OBJS}
	ar rcs ${NAME} ${OBJS}

clean:
	rm -f ${OBJS}

fclean: clean
	rm -f ${NAME}

re: fclean all

.PHONY: all clean  fclean re
